### ISSUE TITLE
Community SignUp form fields looking weird

### ISSUE THREAD

**Issue by shakti97** [codeuino/social-platform-donut-frontend#101]
![screenshot 25](https://user-images.githubusercontent.com/30585570/53681608-efe4d300-3d11-11e9-9744-8762c0f01a86.png)
 you can see the bordered ends of the fields

**Comment by shakti97** [comment]
Already sent PR against this issue

**Comment by Rupeshiya** [comment]
@shakti97 , before sending any PR please get assigned with  the issue by asking to the project maintainer.

**Comment by shakti97** [comment]
sorry actually i didn't know this, i m new to OSS . Will apply this step before sending the next PR. I hope you don't mind :)

**Comment by jaskirat2000** [comment]
No worries. Looking forward to it.

**Comment by Rupeshiya** [comment]
> sorry actually i didn't know this, i m new to OSS . Will apply this step before sending the next PR. I hope you don't mind @Rupeshiya :)

cool @shakti97

**Comment by arghac14** [comment]
Hey @Rupeshiya can I work on this is anyone is not working?

**Comment by Rupeshiya** [comment]
@arghac14  There is already a PR for this issue .So please look for other issues .

**Comment by lakshyabatman** [comment]
Please close this issue @shakti97
