### ISSUE TITLE
Frontend logic for upvote and downvote in other-landing.ejs

### ISSUE THREAD

**Issue by lakshyabatman** [codeuino/social-platform-donut-frontend#108]
In my merged pr, I've updated the upvotes and downvotes logic and on clicking the upvote or downvotes button throws off the ajax request which updates the database although, the frontend for the success or failure is required. 

**file** 
Other-landing.ejs , you will find ajax script on it, and I added a comment for guidance.

**Comment by shreyanshjn** [comment]
I would like to take up this issue.

**Comment by lakshyabatman** [comment]
Yes, sure :)

**Comment by shreyanshjn** [comment]
@lakshyabatman I could see only one project which seems to be hard-coded.

![project](https://user-images.githubusercontent.com/34000568/53975663-65dea500-412b-11e9-9864-6a2edfc6bde1.png)

Can you help me on how could I add new project?
I need this in order to solve the issue.

**Comment by lakshyabatman** [comment]
@capedcrusader23 , please can you help.

If you go to db folder, there are projects.txt, which contains the projects and you can work on it.
@shreyanshjn

**Comment by shreyanshjn** [comment]
@lakshyabatman , since we are moving to vue, should I now edit the ejs file to resolve this issue?
