### ISSUE TITLE
signup problem 

### ISSUE THREAD

**Issue by mark-nakachon** [codeuino/social-platform-donut-frontend#125]
### **Description of the problem**
this problem is about signing up a user although there is a sign up page it is not styled and the post request to /userlogin route is not working and when a user signs up his/her details are not stored in the database 

### **How to solve**
i will solve this issue by adding a /signup route and handle the logic of signing up the user and saving the details in the database and logging in the user after signing up

### **Expected Outcome**
after resolving this issue a user can sign up and his/het details will be succesfully saved in the database

i am assigning this issue to myself

**Comment by jaskirat2000** [comment]
Sounds cool, go ahead
