### ISSUE TITLE
Need a new realtime notification system in navbar for user pannel. The notification must bundle all the notification send at time 

### ISSUE THREAD

**Issue by capedcrusader23** [codeuino/social-platform-donut-frontend#13]

**Comment by moulikcipherX** [comment]
Hy I would love to work on this.

**Comment by jaskirat2000** [comment]
Sure please go ahead

**Comment by moulikcipherX** [comment]
Hy, can you tell me which user panel are we suggesting here?

**Comment by moulikcipherX** [comment]
what type of notification we have to send.

**Comment by svr8** [comment]
Hey! is anyone working on this issue?
I have the same doubt as above.. is there any API where I keep checking if there are any notifications?
I plan to implement a Pub/Sub mechanism so its easy to handle notifications

**Comment by svr8** [comment]
Please review PR #120
