### ISSUE TITLE
Adding Netlify bot to preview Deploys 

### ISSUE THREAD

**Issue by debck** [codeuino/social-platform-donut-frontend#130]
### **Description of the problem**
Adding netlify bot to the project for Deploy previews. Any front-end related PR can be  easily previewed and would provide a better solution for maintainers.

### **How to solve**
We can easily do that by configuring  our GitHub account with netlify and giving permission to the repo.

**Comment by jaskirat2000** [comment]
This sounds good. Make a request for it. I will merge
