### ISSUE TITLE
Add FLOW for typechecking

### ISSUE THREAD

**Issue by debck** [codeuino/social-platform-donut-frontend#135]
### **Description of the problem**
Add Flow to the existing project. It adds static typing to JavaScript to improve developer productivity and code quality.

### **How to solve**
using flow for nodejs. Resourse: https://codeburst.io/getting-started-with-flow-and-nodejs-b8442d3d2e57

**Comment by MohammadHasham** [comment]
Can I work on this?

**Comment by prateekiiest** [comment]
Sure you can go ahead

**Comment by MohammadHasham** [comment]
Done this and made PR as well.
