### ISSUE TITLE
No  footer after login .

### ISSUE THREAD

**Issue by Rupeshiya** [codeuino/social-platform-donut-frontend#136]
### **Description of the problem**
_Footer is not there after logged in_

### **How to solve**
_Render the same footer as before login _

### **Screenshot**
_Add necessary screenshot wherever required_

### **Expected Outcome**
_Footer will be there to navigate easily after login._

**Comment by Rupeshiya** [comment]
@iamgrawal  Should I go ahead ?

**Comment by jaskirat2000** [comment]
Footer regarding what ?

**Comment by Rupeshiya** [comment]
Only in the landing page there is footer but not in all the pages .I think It should be in all pages , correct me if am wrong ??

**Comment by arghac14** [comment]
@Rupeshiya assign this to me.

**Comment by sarthak77** [comment]
Can i take this one?

**Comment by shahkv95** [comment]
@Rupeshiya I would like to take up this oppurtunity and contribute for the required output.
May I proceed for the same?
