### ISSUE TITLE
Need rectification in schema

### ISSUE THREAD

**Issue by capedcrusader23** [codeuino/social-platform-donut-frontend#146]
### **Description of the problem**
The schema can be rectified for user and project

### **How to solve**
look for the data types and the mappings required by mongodb
### **Screenshot**
_Add necessary screenshot wherever required_

### **Expected Outcome**
A robust schema for user and projects

**Comment by lakshyabatman** [comment]
Why I can't find the upDownVote function, in the controller file?

**Comment by capedcrusader23** [comment]
@lakshyabatman we are working on finding that

**Comment by kiransaha** [comment]
Pr requested

**Comment by lakshyabatman** [comment]
@capedcrusader23 , I'll add pr for the again

**Comment by lakshyabatman** [comment]
I'm taking up the issue.

**Comment by kiransaha** [comment]
THe pr is already in process
