### ISSUE TITLE
Add  backend validation in submit project form

### ISSUE THREAD

**Issue by Rupeshiya** [codeuino/social-platform-donut-frontend#149]
### **Description of the problem**
_There is no validation in submit project form_

### **How to solve**
_Add frontend and backend validation_

### **Screenshot**
_Add necessary screenshot wherever required_

### **Expected Outcome**
_Users can not submit form without filling the required information_
@devshiva619  should I work on this ?

**Comment by capedcrusader23** [comment]
Use express-validation for this
