### ISSUE TITLE
A front end page where user can see current details and can change them.Front end required only

### ISSUE THREAD

**Issue by capedcrusader23** [codeuino/social-platform-donut-frontend#15]

**Comment by sagarchoudhary96** [comment]
will something like this works 
<img width="1581" alt="screenshot 2018-10-02 at 10 24 55 am" src="https://user-images.githubusercontent.com/16102594/46329824-8448ed80-c62d-11e8-83fe-648a178c4b70.png">

**Comment by capedcrusader23** [comment]
yep its is fine

**Comment by jaskirat2000** [comment]
this is perfect go ahead and good luck with it @sagarchoudhary96

**Comment by AviBomb** [comment]
![screenshot from 2018-12-02 02-02-06](https://user-images.githubusercontent.com/38415320/49332725-59045f80-f5d8-11e8-9616-0c333fcb871a.png)
![screenshot from 2018-12-02 02-16-27](https://user-images.githubusercontent.com/38415320/49332726-599cf600-f5d8-11e8-9c96-dd575d40977e.png)
Hey this is a very simple version without any bootstrap that i had worked on a while ago, so there shouldn't be any issue with how to go about editing the information while viewing the existing data .In one of the pictures i click the edit button the data is fed back to the fields of the list to read in the data which can be seen in the other picture where it can be edited and submitted again to be stored. I would love to help in making some thing similar to the picture above using bootstrap so do let me know if i can help with that :)

**Comment by jaskirat2000** [comment]
@AviBomb thanks for reaching out. I would suggest that go with a design that has been made by @sagarchoudhary96. You can go with similar approach and make aure you add everything like what we see on other social sites like facebook and twitter

**Comment by Sweta271097** [comment]
@jaskirat2000 Is someone assigned to this issue or can I work on it?
