### ISSUE TITLE
Logout Button not attached to any Route

### ISSUE THREAD

**Issue by imdhruvgupta** [codeuino/social-platform-donut-frontend#153]
### **Description of the problem**
There is no route attached to the Logout button on the main-landing view. Hence the button is no functional.

### **How to solve**
Create a logOut route and add the redirect to that route onClick of the logout button.

### **Screenshot**
![Screenshot 2019-03-12 at 10 31 40 AM](https://user-images.githubusercontent.com/32172694/54175773-0d543280-44b2-11e9-800c-fc44720510b7.png)

### **Expected Outcome**
On Clicking the Log Out  button the user will be logged out and will be redirected to the home page.

**Comment by imdhruvgupta** [comment]
I am assigning this issue to myself and will be creating a PR soon enough.
Thanks,

**Comment by Rupeshiya** [comment]
@imdhruvgupta  are you working on this or can I send PR ??

**Comment by imdhruvgupta** [comment]
> @imdhruvgupta are you working on this or can I send PR ??
@Rupeshiya I got a little busy. Leave this for me, I will send a pr in a couple of days.

**Comment by Rupeshiya** [comment]
sure go ahead @imdhruvgupta

**Comment by lakshyabatman** [comment]
@imdhruvgupta any progress?

**Comment by mark-nakachon** [comment]
if u assign this issue to me i can fix it in less than an hour

**Comment by TG1999** [comment]
Thanks @mark-nakachon this issue is resolved already #166

**Comment by TG1999** [comment]
Please, someone, close this issue

**Comment by sarthak77** [comment]
Is the PR merged as route is not working for me?

**Comment by TG1999** [comment]
You are on which branch @sarthak77 development or master

**Comment by sarthak77** [comment]
development

**Comment by TG1999** [comment]
Yes, I checked in my PR it was only for other_landing.ejs but it should be also for main_landing.ejs.No problem making a PR for it in 5 minutes.

**Comment by TG1999** [comment]
I have made the PR thanks again for reminding.
