### ISSUE TITLE
Backend code for updating the personal information is not  working, also add backend validation and separate css codes from settings.ejs

### ISSUE THREAD

**Issue by Rupeshiya** [codeuino/social-platform-donut-frontend#157]
### **Description of the problem**
_Backend code for updating the profile is not working, the code in settings.ejs is not refactored and there is no validation in the backend as well._

### **How to solve**
_Setup the routes properly for making update details request work properly, add validation and separate the css and js files form settings.ejs_

### **Expected Outcome**
_Profile will be updated in backend_

@capedcrusader23  @iamgrawal should I work on this ?

**Comment by jaskirat2000** [comment]
Sure go ahead
