### ISSUE TITLE
Prototype for screen sharing for idea 5 of GSoC

### ISSUE THREAD

**Issue by TG1999** [codeuino/social-platform-donut-frontend#164]
### **Description of the problem**
There is no feature of screen sharing in DONUT as for now. I am sharing a prototype for this 
https://github.com/TG1999/task_screen_sharing. Instructions are given in readme.

### **How to solve**
This is only a prototype. Try to scale it like adding rooms and namespaces for multiple meetings and please try peer to peer communication as suggested by mentors and this is only for chrome for now also look at how you will do it for Firefox. And please try to make it a standalone software which other organizations can also use as suggested by mentors.

### **Expected Outcome**
Successful integration of this feature in DONUT platform.

**Comment by jaskirat2000** [comment]
Thanks for it l. You can put the code also in someway

**Comment by TG1999** [comment]
@jaskirat2000 I am not able to get it, in which way should I be putting the code.

**Comment by prateekiiest** [comment]
@TG1999 are you working on this? 

Let us know when you open a PR

**Comment by TG1999** [comment]
I am not working on this project I wanted to share the code to the
community so @jaskirat2000 suggested me to open an issue for it. This is a
prototype only which others could incorporate in their proposal .
