### ISSUE TITLE
Implement a system to calculate popular proposed projects

### ISSUE THREAD

**Issue by capedcrusader23** [codeuino/social-platform-donut-frontend#21]
Come up with a solution to show popular project
Must be the ratio of number of likes/number of dislikes:- max of this will most popular one

**Comment by jaskirat2000** [comment]
sure @rishabhp99 please go ahead and make your PR. Good luck

**Comment by Dhroov7** [comment]
@jaskirat2000 @devshiva619 Can i also contribute anything in this issue?
