### ISSUE TITLE
Make front end of landing page and other pages responsive 

### ISSUE THREAD

**Issue by capedcrusader23** [codeuino/social-platform-donut-frontend#22]

**Comment by justiceotuya** [comment]
dibs

**Comment by aksharanigam1112** [comment]
could you please explain in what way do you mean the responsive page ???

**Comment by capedcrusader23** [comment]
yep,if you can see landing page when user log in the page have upvote downvote button the count should have fade in effect and should move upwards for upvote and move downwards in downvote with the count of respective button.The proposed project on right side should be highlighted in some way depends on your creativity.

**Comment by AviBomb** [comment]
![screenshot from 2018-12-02 02-27-17](https://user-images.githubusercontent.com/38415320/49332816-20fe1c00-f5da-11e8-8ccf-77197b94ac6f.png)
![screenshot from 2018-12-02 02-02-06](https://user-images.githubusercontent.com/38415320/49332818-25c2d000-f5da-11e8-93b6-14b311a34f30.png)
Hey this is a very simple version without any bootstrap that i had worked on a while ago, so there shouldn't be any issue with how to go about moving the data dynamically based on the information of up-votes and down-votes fed into the system while continuing to view the existing data .In one of the pictures i click the sort button (Indicative of a Down-vote or an Up-vote in this example) the data is sorted in the other picture where it can be seen sorted based on the ranking given to each user (Over here sorted based on the Up-votes and Down-votes instead). I would love to help in making some thing similar to that in the picture with the same functionality at the same time using bootstrap to make it look much more presentable so do let me know if i can help with that :)

**Comment by jaskirat2000** [comment]
Hey this page is the feed page i would suggest you to move to this issues for this

**Comment by jaskirat2000** [comment]
https://github.com/codeuino/frontened/issues/14
