### ISSUE TITLE
Adding image upload feature

### ISSUE THREAD

**Issue by lakshyabatman** [codeuino/social-platform-donut-frontend#222]
### **Description of the problem**
Backend logic for uploading image is not done.
### **How to solve**
Seek help from @devshiva619 , so he'll guide you to setup image upload using AWS.

### **Expected Outcome**
User can upload images, for profile picture, event cover, project cover.

**Comment by subhamX** [comment]
I would like to take this issue.

**Comment by TG1999** [comment]
@devesh-verma can you tell the location where should I save the image file, currently I am sending a PR with the local location at the server, I will make the change afterward.
