### ISSUE TITLE
Fully implement the forgot password

### ISSUE THREAD

**Issue by Rupeshiya** [codeuino/social-platform-donut-frontend#235]
### **Description of the problem**
_Change password function is only taking email and password and looking for the user and sending back the user details_

### **How to solve**
_Update the chagePass function of forgot password controller to update the password_

### **Screenshot**
_Add necessary screenshot wherever required_

### **Expected Outcome**
_Should update the password_

**Comment by TG1999** [comment]
Okay with which password it should update it then ? 😊

**Comment by TG1999** [comment]
Let me explain you the mechanism before you open further issues like this, first user give its email id, then user receives an email. After clicking on the link the user will be redirected to page if the link is verified(change pass) this work is done till now, the redirection part is left where I will get the new password of user.

**Comment by TG1999** [comment]
So please close this issue. 😄

**Comment by Rupeshiya** [comment]
@TG1999 But to change the password you should have to take the password from frontend and then update that instead of only sending the success msg after getting redirected to that link.

**Comment by TG1999** [comment]
Let me explain that since we are now using Vue as front end framework, what will happen now. The link that I have given in email will redirect the user to front end with the given parameters, then front end will send an axios request to backend to verify the given link and backend will send a message accordingly. After getting that message from backend front end will decide that will it allow user to change the password. If it allows an input box will be provided so user can enter the new password and then password will be reseted at backend. I think now you can understand the code.

**Comment by Rupeshiya** [comment]
@TG1999 **This is the code where you are taking email for forgot password and then sending email to that user with a URL like http://localhost:3000/email/password and when user will click on that then from frontend axios request will be sent to the backend where you are checking for the user with that email and password if that exists then you are sending the success message else you are sending a status of 404, 
Now assume if then user exists then will be redirected to a form in frontend where user can input the new password and will submit and password will be changed. But Can you please point me where you are recieving that new password in backend and update the old password with the new one in backend?.** 
```getById:async(req,res)=>{
      try{
        let user=await User.findOne({email:req.body.email});
        console.log(user.pass)
        var mailOptions = {
            from: cred.user,
            to: req.body.email,
            subject: 'Forgot Password',
            text: `Hi please use this link ${os.hostname}/forgot/${req.body.email}/${user.pass}`
          };
          transporter.sendMail(mailOptions, function(error, info){
            if (error) {
              console.log(error);
            } else {
              console.log('Email sent: ' + info.response);
            }
          });}
          catch (err) {
            console.log(err)
            res.status(400).json({
                status:0,
                msg:'Failed to get user'
            })
        }         
    },
    changePass: async(req,res)=>{
      try{
      let user=await User.findOne({email:req.params.email,pass:req.params.pass});
      if(user)
      {
        res.json({
          status:1,
          msg:'Success',
          email:req.param.email
      })
      }
      else{
        res.status(404).json({
          status:0,
          msg:'No user found'
      }) 
      }
    }
    catch(err){
      console.log(err)
            res.status(400).json({
                status:0,
                msg:'Failed to change password'
            })
    }
}```

**Comment by TG1999** [comment]
Yes it's not implemented right now and that part is left for now,but you have said that I should have not send the message I should have redirected it instead of sending the message, so i explained it to you the current flow does not need to be changed it has to be expanded only.

**Comment by TG1999** [comment]
Their won't be any redirections from backend and we also can't now redirect from backend it all will happen at front end, if you can help in front end i can explain you what is to be done 😄

**Comment by Rupeshiya** [comment]
> Yes it's not implemented right now and that part is left for now,but you have said that I should have not send the message I should have redirected it instead of sending the message, so i explained it to you the current flow does not need to be changed it has to be expanded only.

That's why I changed the issue to fully implement that feature so that we can keep track of the features.

**Comment by Rupeshiya** [comment]
> Their won't be any redirections from backend and we also can't now redirect from backend, it all will happen at front end, if you can help in front end i can explain you what is to be done

When I will start working on the frontend side of this project then surely ping you. @TG1999

**Comment by harshithpabbati** [comment]
Can I work on this issue ?

**Comment by Rupeshiya** [comment]
@harishchennupati I have already implemented this feature in a PR but it is closed by @devesh-verma .Don't know why.
cc @devesh-verma Please update him
