### ISSUE TITLE
Add some PWA features

### ISSUE THREAD

**Issue by Rupeshiya** [codeuino/social-platform-donut-frontend#242]
### **Description of the problem**
_Add some PWA features like making it installable or working offline_

### **How to solve**
_Take permission from user to install the App and then install, for working in offline mode use caching strategy_

### **Screenshot**
_Add necessary screenshot wherever required_

### **Expected Outcome**
_Web app will behave as native app_

**Comment by kg-kartik** [comment]
Can i work on this?
