### ISSUE TITLE
Add manifest.json file for PWA

### ISSUE THREAD

**Issue by Rupeshiya** [codeuino/social-platform-donut-frontend#243]
### **Description of the problem**
_To implement the PWA feature there should be a manifest.json file_

### **How to solve**
Use the links given below as a references to start working. Basically PWA is a feature that make a web app to behave like a native app. 
1. Get idea of PWA (https://codelabs.developers.google.com/codelabs/your-first-pwapp/#0)
2. How to add manifest.json (https://codelabs.developers.google.com/codelabs/your-first-pwapp/#3)

### **Screenshot**
_Add necessary screenshot wherever required_

### **Expected Outcome**
_Project should be ready to implement PWA_

**Comment by ayushnagar123** [comment]
I guess we already have menifest.json in client/public in the development branch. Do we need any updates in that?

**Comment by Rupeshiya** [comment]
@ayushnagar123 There are lots of things that need to be added in manifest.json but for since we are not focusing on PWA features so this issue needs to be fixed in future. For now you can work on the other issue.
Thanks for looking for issues to fix.
