### ISSUE TITLE
Welcome email feature

### ISSUE THREAD

**Issue by TG1999** [codeuino/social-platform-donut-frontend#249]
### :thinking: What you will need to know
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Welcome Email Feature
Send a welcome email whenever new user signup to DONUT platform. We have currently put designing tasks in GCI, In this task student have to trigger an email whenever the signup route is hit. Data of users will be entered in the email template and will be sent to the user's email address, with some greetings.

### Requirements 
Node.JS
NodeMailer

### Step By Step :1234: 
- 🙋 Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
- :memo:  Mention your Google-Code in participant ID (userID) in the comment.
-  Install DONUT on your system go through readme.md in development branch for this purpose
- After installing DONUT install dependencies of server and client, go through readme.md inside both the folders (for this issue only server-side is required)
Link to readme https://github.com/codeuino/Social-Platform-Donut/tree/development/server
- After that get into server folder and do `npm start` (server will setup on localhost:3000)
- Then write a function in file `email.controller.js` controllers folder, pass some parameters like name, email from
https://github.com/codeuino/Social-Platform-Donut/blob/development/server/controller/authcontroller.js
to the function in email.controller.js 
(export function from `email.controller.js` and import it in authcontroller.js in scope of signup function)
The function should look like this
```
module.exports={
sendEmail:sendEmail(email,name)=>{
// Code for sending email, check below for NodeMailer reference
var nodemailer = require('nodemailer');
var cred=require('../credentail')
var transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: cred.user,
    pass: cred.pass
  }
});

var mailOptions = {
  from: cred.user,
  to: email,
  subject: 'Sending Email using Node.js',
  text: 'Hi!'+name+'thanks for Joining Codeuino'
};

transporter.sendMail(mailOptions, function(error, info){
  if (error) {
    console.log(error);
  } else {
    console.log('Email sent: ' + info.response);
  }
}); 
}
}
```
- Then using Postman send a POST request on localhost:3000/auth/signup like this
![Screenshot from 2019-11-11 15-14-34](https://user-images.githubusercontent.com/34160672/68577523-4821c680-0496-11ea-9ca2-5d008d16a853.png)
Link to Postman https://www.getpostman.com/
- After hitting the POST request user should get an email

:floppy_disk: Commit your changes

:twisted_rightwards_arrows: Start a Pull Request. There are two ways how you can start a pull request:

If you are familiar with the terminal or would like to learn it, [here is a great](https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github) tutorial on how to send a pull request using the terminal.

You can also edit files directly in your browser and open a pull request from there.

:checkered_flag: Done Ask in comments for a review :)
### Acceptance Criteria :smile: 
Whenever new user signups an email should be sent.

### Rejection Criteria 
If the given feature is failing or not working properly. But not to worry some mentor will help you in getting this feature implemented. :+1: 

 ### **Expected Outcome**

 Learning some basic Node.JS and interacting with the APIs
 
:handshake: Share the issues you encounter along the way and help others solve theirs. :speech_balloon: Chime in below in a comment to cooperate with others who are also
 working on this task.
 
 :hand: Report back at the above issue once you succeed, to encourage others and share what worked for you!

### Resources & References (Where to Start)
Currently, all the code is on the development branch and the signup function is currently here with all the information that is needed to send the email like email address of the user, etc.
https://github.com/codeuino/Social-Platform-Donut/blob/development/server/controller/authcontroller.js
So you have to trigger your function in the scope of signup function.
Some reference material
https://nodemailer.com/about/
 ### **Extras**

 Just follow the readme whenever you are stuck goto
 https://codeuino.slack.com/ to ask your doubts.

**Comment by jugshaurya** [comment]
can i take this issue ? I am looking for GSOC 2020 and new to open source in the way of contributing to others project . I think this can help me understanding opensource and contribute to GSOC

**Comment by TG1999** [comment]
This issue is for GCI students only, you can look for other issues that are not labelled as GCI.

**Comment by AuraOfDivinity** [comment]
I'd like to work on this issue.

**Comment by jaskirat2000** [comment]
Sure go ahead.
