### ISSUE TITLE
Adding Netlify Bot to preview deploys

### ISSUE THREAD

**Issue by sastava007** [codeuino/social-platform-donut-frontend#261]
### **Description of the problem**
Implement a feature to preview deploys using Netlify Bot, this will help in maintaining continious integration and development. It will also help the mentors to review any front-end related PR more easily.  

Before working on this issue, you should know what the hell in this world **Netlify** is and why do we even need it?
Netlify is hosting platform that provide service of continious deployment directly from Git for serverless static websites. We need it to preview our deploys before pushing them to production.

### **Prerequisites**
A basic understanding of the struture of codebase is required.

### **Getting started**😀
Before start working on this issue, leave a comment with your GCI I'd so that two people not end up working on same issue. 

### **How to solve**👨‍💻
Sound too complicated? Let’s focus in.
First of all you should setup the project on your end and for that follow the steps mentioned here in [readme](https://github.com/codeuino/Social-Platform-Donut/blob/master/README.md) file.

Once you have successfully setup the project you are already half way done👏🙌, so now coming to actual problem and how to solve it.
It's not that difficult you just need to create a .toml file(TOML is a markup language) containing the build information of CLIENT side of project and allow permissions from the github repo(ask your mentor to allow permissions for the same).

You can refer to this wonderful [https://hackernoon.com/netlify-continuous-deployment-github-react-lambdaschool-67f3ae658d31](article) article for reference purpose which contains step by step guide for achieving the same.

### **Acceptance Criteria**😄
You should be able to successfully setup Netlify bot.

### **Rejection Criteria**😖
Don't worry if you could not successfully solve the issue, we are there to help you. Feel free to reach to us and share your problem. 🤝 👍

### **Expected Outcome**
Once Netlify bot is setup, we'll be able to preview any PR before merging it to development.

After solving the issue, you should commit your changes and submit a pull request(PR). In order to submit a PR there are two ways, if you know about terminal or wanted to learn then here's a great article [https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github](url) which you can follow. 
The other way is simpler and you can open a PR through browser only.

**Comment by sastava007** [comment]
@vaibhavdaren It's a beginner frinedly issue as it doesn't need any such prerequisite so you can also add good-first issue label too.

**Comment by saksham93** [comment]
I wish to work on this issue.
/assign

**Comment by sastava007** [comment]
@saksham93 
Thanks Saksham, for showing interest in contributing to Donut platform. But this task is meant only for GCI'19 students, feel free to choose any other task which is not labelled as GCI.
