### ISSUE TITLE
Designing Admin Dashboard

### ISSUE THREAD

**Issue by TG1999** [codeuino/social-platform-donut-frontend#263]
### :thinking: What you will need to know
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Designing Admin Dashboard
Design a Admin Dashboard for Codeuino, The design should contain some basic buttons or sections like this.

    

- Button for Admins can add members to the community.
- Button for Blocking users ( Giving access to block people)
- Section for Analytical representation (This will help community view stat for their posts which can be shown through popularity/most viewed,etc )
- Section for Contribution on various projects 
- Section for Project/Articles/blogs and other feeds posted by community
- Section for Comments made by people on any community post
 - Section for Profile with all details (Giving access to delete any post)
 - Section for allowing to give them access for the "settings" of the community
 - Section for Activity logs ( This feature will describe about followings, comments, Upvote/Downvote, stare, pinned things( posts/projects/events/etc)

### Requirements 
Basic Designing Skills
### Step By Step :1234: 
- 🙋 Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
- :memo:  Mention your Google-Code in participant ID (userID) in the comment.
-  Store your designs inside design/dashboard folder
 ### **Expected Outcome**

 Learning some Designing skills
 
:handshake: Share the issues you encounter along the way and help others solve theirs. :speech_balloon: Chime in below in a comment to cooperate with others who are also
 working on this task.
 
 :hand: Report back at the above issue once you succeed, to encourage others and share what worked for you!

### Resources & References (Where to Start)
Some reference material
https://zapier.com/blog/learn-design-elements-basics/
Example of Dashboard
https://webapphuddle.com/dashboard-design-examples/
The actual text that needs to be their will be given in some time till then you can use some lorem ipsum text for checking formatting.
https://www.lipsum.com/

 ### **Extras**
 Just follow the readme whenever you are stuck goto
 https://codeuino.slack.com/ to ask your doubts.

**Comment by theprover97** [comment]
Hey @TG1999 , I would like to work on this.
