### ISSUE TITLE
Improve the UI design of the Profile, Login and Signup pages

### ISSUE THREAD

**Issue by SiddharthSimharaju** [codeuino/social-platform-donut-frontend#267]
### **What you need to know**
Basic Designing Skills and vague knowledge of tools used in the User Interface (UI) design.

### **Requirements**
- UI design skills
- Familiarity with designing Softwares like Figma, Invision(webapp/application) or Adobe XD(application)

### **Improve the UI design of the Profile, Login and Signup pages**
We want to redesign the Donut platform. Improve the overall design and revamp it with new design trends in the market. We want you to design clean, professional and unique designs for Profile, Login and Signup pages.

### **Step By Step**
- Install Donut application locally on your machine ([Installation Guide](https://github.com/codeuino/Social-Platform-Donut))
- Visit the application and understand the purpose and the motivation behind the platform.
- Previous designs can be found here (https://docs.codeuino.org/donut/client-side)
- Be creative and make your art aesthetically associated with Donut Application.
- Design Profile, Login and Signup pages for the donut application. Make sure all three pages follow a specific design scheme if your choice. [[Login Page Examples](https://www.google.com/search?safe=active&rlz=1C1RLNS_enIN841IN841&biw=1366&bih=657&tbm=isch&sxsrf=ACYBGNQAhUMph16gT8O_GM-7IvClX681pQ%3A1574134114847&sa=1&ei=YmHTXdWbM9LA3LUP4Zid8Ak&q=login+pages&oq=login+pages&gs_l=img.3..0i67l2j0l2j0i67l2j0l4.18732.19254..19385...0.0..0.251.867.2-4......0....1..gws-wiz-img.QHzgyA9SKGE&ved=0ahUKEwjV1PnFqvXlAhVSILcAHWFMB54Q4dUDCAc&uact=5)], [[Signup Page Examples](https://www.google.com/search?safe=active&rlz=1C1RLNS_enIN841IN841&biw=1366&bih=657&tbm=isch&sxsrf=ACYBGNTjt3-K9RFYECkWuqGS-zIm7X-uHg%3A1574134135819&sa=1&ei=d2HTXe3MMerWz7sPxuiusAk&q=Signup+pages&oq=Signup+pages&gs_l=img.3...37826.38742..38905...0.0..0.440.1507.2-3j1j1......0....1..gws-wiz-img.1gNetngplOg&ved=0ahUKEwit5PnPqvXlAhVq63MBHUa0C5YQ4dUDCAc&uact=5)], [[Profile Page Examples](https://www.google.com/search?safe=active&rlz=1C1RLNS_enIN841IN841&biw=1366&bih=657&tbm=isch&sxsrf=ACYBGNSyHh9YDekQjdLVKeZDebpGFNaUug%3A1574134213589&sa=1&ei=xWHTXYnLI47Tz7sPifug0A4&q=web+profile+page+ui&oq=web+profile+page+ui&gs_l=img.3..0l2.3808.4338..4585...0.0..0.253.923.2-4......0....1..gws-wiz-img.......0i7i30.bR-iNBNXz7A&ved=0ahUKEwjJwYT1qvXlAhWO6XMBHYk9COoQ4dUDCAc&uact=5)]
- Export your design as JPEG/PDF and the open file format.
- Also, provide a document consisting of the process of design and the reasons behind design decisions.
- Get the design verified by the mentors.
- Improve as per the mentor's guidance.

### **Expected Outcome**
Learning some basic UI (User Interface) designing skills and tools like Adobe XD, Figma, Gravit Designer, and Invision.

### **Acceptance Criteria**
- The Profile, Login and Signup pages should look clean and professional and should be of the highest quality. Strictly follow one scheme for all three designs.
- Attach a document explaining the process of design.
- The formats that the deliverables of the three page designs should contain are - PDF/JPEG and the open file.

### **Rejection Criteria**
- If you create a design similar to something you found on the web.
- If the design of two participants is found to be copied they both will be reported and will be disqualified from the task.
- Give attribution to any online resource you use in the design. Failing to do that will disqualify from the task.

### **Resources & References**
- UI design tips are available on net [Link1](https://www.mockplus.com/blog/post/learn-ui-design),  [Link2](https://uxdesign.cc/ultimate-start-guide-for-beginner-ux-ui-designer-b848be089589)
- You can find inspiration from [[Pintrest-Login/Signup Pages](https://in.pinterest.com/search/pins/?q=login%20page%20design&rs=typed&term_meta[]=login%7Ctyped&term_meta[]=page%7Ctyped&term_meta[]=design%7Ctyped)], [[Pintrest-Profile Pages](https://in.pinterest.com/search/pins/?q=profile%20page%20design&rs=typed&term_meta[]=profile%7Ctyped&term_meta[]=page%7Ctyped&term_meta[]=design%7Ctyped)]
- For Colors you can take reference from [Material Color Palette](https://www.materialpalette.com).
- For typography, you can find samples at [Google Fonts Libraries](https://fonts.google.com).

### **Extras**
https://codeuino.slack.com/ to ask your doubts.

**Comment by theprover97** [comment]
Hey @SiddharthSimharaju , can I now work in this as GCI has ended?
