### ISSUE TITLE
Make a frontend Community ( Organisation ) dashboard for this Platform

### ISSUE THREAD

**Issue by jaskiratsingh2000** [codeuino/social-platform-donut-frontend#27]
Make a fronted Community ( Organisation ) dashboard for this Platform.

Just like we have dashboard in LinkedIn, Twitter, Facebook etc for the organisation to make an do changes.

So this has to be made in this way:
Reference to these examples:
https://goo.gl/images/6i4dC6
https://goo.gl/images/kLk3rM
https://goo.gl/images/qrtmm1

It should include what all things are required in the dashboard for a community

**Comment by SriAish** [comment]
I am doing this!

**Comment by jaskirat2000** [comment]
Sure @aishwarya please go ahead and send you PR

**Comment by vaibhavdaren** [comment]
@SriAish  Oki cool

**Comment by SriAish** [comment]
I have made a pull request with a dashboard for community/organization

**Comment by HarshCic** [comment]
Can i work on this @jaskirat2000 for 2019 GSoC

**Comment by vaibhavdaren** [comment]
@HarshCic  you may work on it.
