### ISSUE TITLE
Provide loopholes inside documentation

### ISSUE THREAD

**Issue by TG1999** [codeuino/social-platform-donut-frontend#273]
### :thinking: What you will need to know
Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Provide loopholes inside documentation
Try to setup DONUT on your system with the help of mentors, then see what steps are missing or wrongly written inside the documentation.
The steps should be valid and relevant for this task to be accepted.

### Requirements 
Critical Thinking
Schema Designing

### Step By Step :1234: 
- 🙋 Claim this issue: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

 ### **Expected Outcome**
Problems inside documentation.

:handshake: Share the issues you encounter along the way and help others solve theirs. :speech_balloon: Chime in below in a comment to cooperate with others who are also
 working on this task.
 
 :hand: Report back at the above issue once you succeed, to encourage others and share what worked for you!

### **Acceptance Criteria**
If the points are relevant and improve the documentation.

### **Rejection Criteria**
If it is only a grammatical correction or improvement of vocabulary.

### Resources & References (Where to Start)
- Fork https://github.com/codeuino/Social-Platform-Donut.git and then go to the development branch
- See the steps inside client and server readme for referring the current documentation
 ### **Extras**
 Just follow the readme whenever you are stuck goto
 https://codeuino.slack.com/ to ask your doubts.

**Comment by rajkharvar** [comment]
while following the documentation to run the project locally `package.json` file actually exists on the `master` branch. When I checkout to `development` branch `package.json` file actually disappeared which in turn I was not able to run it locally for development.

Should I fork and repo and install the dependencies when on the `master` branch and commit the result on the `development` branch and then make a pull request? If this was the actual step, please update the documentation to easily set up the project for other developers or else I can update the documentation if possible. Please let me know if I get it wrong.
