### ISSUE TITLE
Auto login user after registration

### ISSUE THREAD

**Issue by sastava007** [codeuino/social-platform-donut-frontend#276]
### **Prerequisites**
- NodeJs
- Authentication using PassportJs
  Don't worry if you are not familiar with Passport, [here's ](https://www.youtube.com/watch?v=6FOq4cUdH8k)a great tutorial to start with.

### **Description of the problem**
Auto-login is quite a popular feature currently used by almost every social networking site from Facebook to Reddit. 
So now coming to what the problem demands, and how we can implement this.
You are supposed to make the user automatically login after he/she completes the registration(sign up) process instead of redirecting to fill the login form again. 

### **How to solve**
Sounds too complicated? Let’s focus in.
You need to setup project on your end and for that follow the steps mentioned here in [readme](https://github.com/codeuino/Social-Platform-Donut/blob/master/README.md) file.

First step first, find the **authcontroller.js** file in /server/controller and go through the code and try to understand how the **signup** and **login** function works. Get stuck somewhere or not sure what a particular statement is meant for then feel free to reach out to mentors through communication channel either on [discord](https://discordapp.com/channels/270264625419911192/644236107088920631) or [slack](https://codeuino.slack.com).

Once you have gained a basic understanding of the authentication process it's time to modify the **signup()** and instead of just returning the response, make an implicit call to **login()** which will login the user and send the generated JWT token as bearer.

### **Acceptance Criteria**
You should be able to successfully implement the auto-login feature.

**Note**
In case you need some reference you can refer to this [stackoverflow](https://stackoverflow.com/questions/16817800/passport-node-js-automatic-login-after-adding-user) answer explaining the same.

**Comment by sastava007** [comment]
@vaibhavdaren 
@jaskirat2000 
Please review!

**Comment by harsh253** [comment]
Hello @sastava007 , I think the discord link is not working and when I am trying to connect to slack, it says **Contact the workspace administrator for an invitation**.
How can I reach to the mentors ? 
Actually , I have some doubts regarding this issue and would like to clear them.
Thanks in advance.

**Comment by sastava007** [comment]
@harsh253 Just visit slack.codeuino.org and register your email, you'll receive an invite link in your mail.

**Comment by amanbora** [comment]
Can I work on this issue?
