### ISSUE TITLE
Make the Create Post, Create Project, Create Event modals responsive

### ISSUE THREAD

**Issue by sastava007** [codeuino/social-platform-donut-frontend#278]
### **Description of the problem**
Currently, the **Create Post**, **Create Project** and **Create Event** modal forms of Donut platform are not responsive. The modals are not responsive for mobile or any other such small-screen devices because of which user need to scroll till down to access the content and buttons are also going hither and thither.

### **Prerequisites**

- CSS
- Basic fundamentals of Responsive Web Design

### **How to solve**
You need to setup the project on your end by following the steps mentioned here in [readme](https://github.com/codeuino/Social-Platform-Donut/blob/master/README.md) file.

Students are supposed to design a responsive web layout for all the three mentioned modal forms.
You are free to use any kind of technology which you are comfortable with, let it be media queries or Bootstrap.

### **Screenshot**
![image](https://user-images.githubusercontent.com/43990819/70653682-f62db580-1c7a-11ea-9121-e38b987dda5a.png)
![image](https://user-images.githubusercontent.com/43990819/70653714-0180e100-1c7b-11ea-9e82-e09f925d6a8e.png)
![image](https://user-images.githubusercontent.com/43990819/70653723-080f5880-1c7b-11ea-8949-2ab236b0ed39.png)

### **Acceptance Criteria**
You should be able to successfully implement the responsive web layout for all the mentioned modal forms. In case you get stuck somewhere, please feel free to reach out to mentors through communication channel either on [discord](https://discordapp.com/channels/270264625419911192/644236107088920631) or [slack](https://codeuino.slack.com).

**Comment by tanujvyas10** [comment]
@sastava007 should i work on this?

**Comment by sastava007** [comment]
@tanujvyas10 Sorry, but this task is meant for GCI students. 
Feel free to find other open issues.

**Comment by tanujvyas10** [comment]
@sastava007  actually there was not any GCI mentioning on this issue that's why I asked . Its fine I will find any other . Thank you :)
