### ISSUE TITLE
Box height in Login/Sign Up form should change dynamically. 

### ISSUE THREAD

**Issue by rohit645** [codeuino/social-platform-donut-frontend#293]
### **Describe the bug**
When clicking on signup form, the box height is not changing accordingly, as a result, content of signup form goes out of signup box.

### **Where was the bug observed**
When you run the project using `npm start` and click on signup form option.

### **Screenshots**
![Screenshot from 2020-02-09 18-04-57](https://user-images.githubusercontent.com/33249010/74102148-dfb2b600-4b66-11ea-8e1f-dbdcbabcebd1.png)
![Screenshot from 2020-02-09 18-05-17](https://user-images.githubusercontent.com/33249010/74102151-e3463d00-4b66-11ea-8be1-d4c599be4a0a.png)

### **Expected Outcome**
![Screenshot from 2020-02-09 18-07-16](https://user-images.githubusercontent.com/33249010/74102216-69fb1a00-4b67-11ea-9e18-5058abf3dd0c.png)
![Screenshot from 2020-02-09 18-09-55](https://user-images.githubusercontent.com/33249010/74102218-6bc4dd80-4b67-11ea-8bc3-ae16fb94400b.png)

**Comment by devesh-verma** [comment]
This has been already fixed.
Hence closing the issue.
