### ISSUE TITLE
Duplicate entries for Email in signup form.

### ISSUE THREAD

**Issue by rohit645** [codeuino/social-platform-donut-frontend#294]
### **Describe the bug**
User Email has been asked two times in signup form.

### **Where was the bug observed**
When you run the project using `npm start` and click on signup form Tab.

### **Screenshots**
![Screenshot from 2020-02-09 18-07-16](https://user-images.githubusercontent.com/33249010/74102381-0d98fa00-4b69-11ea-9137-6a65da47c98b.png)

### **Expected Outcome**
![Screenshot from 2020-02-09 18-20-56](https://user-images.githubusercontent.com/33249010/74102403-34573080-4b69-11ea-9479-314273d2a426.png)

**Comment by amanbora** [comment]
I've made a pull request #299 regarding this issue.
