### ISSUE TITLE
Upcoming events section of dashboard page needs improvement

### ISSUE THREAD

**Issue by harsh253** [codeuino/social-platform-donut-frontend#295]
### **Description of the problem**
The content of the **Upcoming Events** section of the dashboard page is incomplete as of now as per the given design and needs to align with the given design.
Currently, it looks as shown below
### **Screenshot**
![Screenshot from 2020-02-09 18-31-52](https://user-images.githubusercontent.com/32335320/74102564-a0866400-4b6a-11ea-8360-fc6acc070096.png)

### **Expected Outcome**
![required-design](https://user-images.githubusercontent.com/32335320/74102591-ed6a3a80-4b6a-11ea-8eed-322f0f025f1a.png)

**Comment by devesh-verma** [comment]
fixed by #307
