### ISSUE TITLE
Create a pop up to display new project info

### ISSUE THREAD

**Issue by JanviMahajan14** [codeuino/social-platform-donut-frontend#316]
On clicking the button project in the dashboard page a pop needs to be displayed on the page.
I am working on this issue.

**Comment by jaskirat2000** [comment]
Awesome. Go ahead

**Comment by jaskirat2000** [comment]
Make sure you follow the design guidelines. If you need any icons and other things let Siddharth knows about it.

**Comment by JanviMahajan14** [comment]
Sure @jaskirat2000
