### ISSUE TITLE
Create Pop up for displaying and editing Profile Info

### ISSUE THREAD

**Issue by theprover97** [codeuino/social-platform-donut-frontend#317]
Based on the designs released on Figma, we will be creating new Pop-ups for :-
1. Editing Profile
2. Displaying Followers List
3. Adding a Logout option.

**Comment by theprover97** [comment]
I will like to work on this issue.

**Comment by jaskirat2000** [comment]
Sure go ahead.
Anyway here are those designs https://www.figma.com/file/iZvb7rLYRp3Di3wILVQ7V9/CodeUino-Donut?node-id=0%3A1

**Comment by JanviMahajan14** [comment]
Hi @theprover97 If you don't mind Can i work on a pop up to display followers list as already you are working on two other pop ups to display edit profile info and logout feature?

**Comment by theprover97** [comment]
@jaskirat2000 , is the DB schema ready so that we may also add backend integration with the fields.

**Comment by theprover97** [comment]
@JanviMahajan14 , I am collectively working on the 3 popups, so I would like to ask you to let me complete them. If I face any problems then I will forward these to you. Thanks!
