### ISSUE TITLE
Authentication:- Add a Logout button

### ISSUE THREAD

**Issue by sdsahib** [codeuino/social-platform-donut-frontend#32]

**Comment by jaskirat2000** [comment]
Sure go ahead

**Comment by rb007123** [comment]
What exactly @sdsahib we have to add? just a button? nothing else?

**Comment by jaskirat2000** [comment]
Also the backend schema required

**Comment by sdsahib** [comment]
@rb007123 logout routes for github, facebook is already there, we need the logout button to close the session of the user. yes currently we need UI and link that with proper route.

**Comment by nityanandagohain** [comment]
I would like to work on this,

**Comment by jaskirat2000** [comment]
Sure go ahead

**Comment by sweezy793** [comment]
@jaskirat2000 Can I work on this now ?

**Comment by ashish10677** [comment]
Is the issue still open? I would like to contribute.
