### ISSUE TITLE
Improvement of the feed section of the dashboard page

### ISSUE THREAD

**Issue by harsh253** [codeuino/social-platform-donut-frontend#320]
Currently **news feed** in the dashboard page has card like elements which is in a very raw form. This section needs improvement to align with the given designs.
Right now it looks as shown below : 

**Screenshot**
![Screenshot from 2020-02-22 12-14-49](https://user-images.githubusercontent.com/32335320/75087983-f399e700-556c-11ea-9770-bb643f2516f7.png)

**Expected Outcome**
![Screenshot from 2020-02-22 12-15-54](https://user-images.githubusercontent.com/32335320/75087992-16c49680-556d-11ea-89e9-990d5dd10d1b.png)

**Comment by harsh253** [comment]
I would like to work on this issue.

**Comment by jaskirat2000** [comment]
Sure hi ahead. Make sure all the colors remain same

**Comment by harsh253** [comment]
Sure.
