### ISSUE TITLE
Integrate 3rd party authentication

### ISSUE THREAD

**Issue by harshithpabbati** [codeuino/social-platform-donut-frontend#321]
Redesign login and sign up forms according to the designs in figma

https://www.figma.com/file/iZvb7rLYRp3Di3wILVQ7V9/CodeUino-Donut?node-id=0%3A1

**Comment by harshithpabbati** [comment]
I would like to work on this

**Comment by jaskirat2000** [comment]
I think only color changes required rest are fine. The current one looks much better

**Comment by harshithpabbati** [comment]
Oh okay. Then I will integrate login with google, github

Ok ? @jaskirat2000

**Comment by jaskirat2000** [comment]
Sure. Sounds good.

**Comment by harsh253** [comment]
Hi @harshithpabbati. I think integration with github and google will be taken care of in the backend repository. I would suggest you to discuss this with @devesh-verma as well.
