### ISSUE TITLE
Redesign of organisation page

### ISSUE THREAD

**Issue by JanviMahajan14** [codeuino/social-platform-donut-frontend#323]
Currently organisation page don't have much of the functionality so I would like to improve it.
**Current page:**
![Screenshot from 2020-02-23 01-10-24](https://user-images.githubusercontent.com/46385227/75098190-31345980-55d9-11ea-9c78-f444686d4e29.png)
**Expected outcome:**
![Web 1920 – 22](https://user-images.githubusercontent.com/46385227/75098202-5923bd00-55d9-11ea-9ab6-8f0be3c998fe.jpg)

**Comment by JanviMahajan14** [comment]
I would like to work on this issue.

**Comment by jaskirat2000** [comment]
Interesting. Go ahead

**Comment by harsh253** [comment]
Hi @JanviMahajan14 . Are you also working on the pinned post section of this page ? I have actually worked on the feed section of the dashboard page and that same piece of code can be used here and similarly at all such places where posts are required.

**Comment by JanviMahajan14** [comment]
@harsh253 Currently i am working on the other parts present in the org page as you can see in the designs and the component under about us section
![Web 1920 – 23](https://user-images.githubusercontent.com/46385227/75152340-cc8b1300-572e-11ea-98a9-2bac1bb38ff8.jpg)

Once your code is merged we can you that for pinned section. For now let me work on this issue and you can search for some other issue. Hope you will don't have any issue now.

**Comment by harsh253** [comment]
Yeah sure @JanviMahajan14 . Thanks for letting me know. 
Actually the sections like 'Donuts', 'Projects' and 'Events' , they are all a kind of filter which would filter posts from pinned posts section. So maybe you could leave the 'Donuts', 'Projects' and 'Events' part and work on other sections like 'About Us' and Contact section.
