### ISSUE TITLE
Enhancement of User Profile Page

### ISSUE THREAD

**Issue by theprover97** [codeuino/social-platform-donut-frontend#327]
Description

Current Profile page doesn't contain the Profile Description column. Also the settings icon is missing.

Current:-
![Screenshot from 2020-02-24 13-23-34](https://user-images.githubusercontent.com/43466272/75135947-1a8d2000-5709-11ea-97a6-f56c1cce0909.png)

After enhancement:-
![Screenshot from 2020-02-24 13-24-01](https://user-images.githubusercontent.com/43466272/75135971-2e388680-5709-11ea-8dff-9e3a4b2ee009.png)

**Comment by theprover97** [comment]
@jaskirat2000 I am working on this.

**Comment by harsh253** [comment]
@theprover97 are you still working on this or may I take up this issue ?

**Comment by theprover97** [comment]
No, I am not working on this currently. You can go ahead and work on it.

**Comment by harsh253** [comment]
Sure. Thanks for the reply @theprover97 :) . I'll take up this issue then.
@jaskirat2000 , could you please assign this to me ?

**Comment by theprover97** [comment]
@harsh253 I am working on improving the pinned posts section to Material-UI. You can add the profile description and improve the display profile part, but please do so using Material-UI.

**Comment by harsh253** [comment]
Ok. @theprover97 Just a suggestion. You can take up the pinned post section code from news-feed section of dashboard to maintain the same code throughout.
