### ISSUE TITLE
Authentication:- Login with Facebook

### ISSUE THREAD

**Issue by sdsahib** [codeuino/social-platform-donut-frontend#33]
create an authentication for login with Facebook. It's already done with google and GitHub(refer that). Follow the folder structure and pull code from **development** branch and send the PR to same branch.

**Comment by imskr** [comment]
i want to work on it!

**Comment by jaskirat2000** [comment]
Sure go ahead

**Comment by iamgrawal** [comment]
I am reopening this issue, since the authentication system is still not completed.
