### ISSUE TITLE
Add popups to Organizations page

### ISSUE THREAD

**Issue by theprover97** [codeuino/social-platform-donut-frontend#337]
The goal is to add new popups suitable for the Organizations page. We will be starting with following popups:-
1. Community Followers popup
2. Organization Edit popup.

The designs will be same as those on Figma, with change in the data fields.

**Comment by theprover97** [comment]
I will work on this.

**Comment by Rupeshiya** [comment]
@theprover97 What's the status?
Are you working on this?
