### ISSUE TITLE
Big gap between "settings" and other side-nav elements

### ISSUE THREAD

**Issue by tanujvyas10** [codeuino/social-platform-donut-frontend#344]
**Current Issue**
The setting option in side-nav is too much below w.r.t. other elements in side-nav.
![coduino-front](https://user-images.githubusercontent.com/48439116/75602295-cbb8ff00-5ae9-11ea-9d78-430a16c306e9.jpg)

**Expected solution**
The setting option should be in a group with other elements within the side-nav

**If the issue is valid, I would like to work on this issue**
@devesh-verma @jaskirat2000

**Comment by jaskirat2000** [comment]
Okay sure

**Comment by devesh-verma** [comment]
@tanujvyas10 this is intentional.
