### ISSUE TITLE
The title "Organization updates" is scrolling down along with the update list.

### ISSUE THREAD

**Issue by tanujvyas10** [codeuino/social-platform-donut-frontend#345]
**Current Issue**
The title "Organization updates" is scrolling down along with the updates list.
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/48439116/75602727-b8a82e00-5aed-11ea-8e27-5d3966b946c1.gif)

**Expected outcome**
The title "Organization updates" should be fixed when scrolling down the organization updates list

**If the issue is valid , I would like to work on this**
@jaskirat2000 @devesh-verma

**Comment by jaskirat2000** [comment]
Great

**Comment by tanujvyas10** [comment]
> Great

sir, i have a PR , please review my work

**Comment by jaskirat2000** [comment]
@devesh-verma needs to approve it once then only it will be merged

**Comment by devesh-verma** [comment]
@tanujvyas10 always refer the issue number in your PR.

**Comment by tanujvyas10** [comment]
> @tanujvyas10 always refer the issue number in your PR.

Sir, I have already written "Fixes #345", But I should have written it more precisely. I will keep this in mind in the upcoming PRs.
