### ISSUE TITLE
Changing the signup page to Material UI framework.

### ISSUE THREAD

**Issue by rak-shit** [codeuino/social-platform-donut-frontend#352]
![Screenshot 2020-03-03 at 10 45 42 PM](https://user-images.githubusercontent.com/30564496/75801192-bc171000-5da0-11ea-9792-a614d854ef53.png)

I am working on this.

**Comment by jaskirat2000** [comment]
Okay. I am assuming this will be added on trello board by @Rupesh or by you whosoever gonna maintain for your ease.
