### ISSUE TITLE
Forget password front end

### ISSUE THREAD

**Issue by capedcrusader23** [codeuino/social-platform-donut-frontend#356]
The forget password functionality has been added in backend.Create a front-end flow for the same.
![Screenshot 2020-03-05 at 12 08 49 AM](https://user-images.githubusercontent.com/37747717/75911410-8728bd00-5e75-11ea-8a99-2b0b2d6686cf.png)

The url to be pushed in history will be auth/reset?queryparams.
the above url will give if the link of password reset is valid or not.
If valid redirect to page where you will have url as:-   url?queryparams.id(the id is the user id used in previous url)and in this page you should have input field and button to submit.

**Comment by tanujvyas10** [comment]
@capedcrusader23  I would like to work on this issue, if you are not working

**Comment by tanujvyas10** [comment]
@devesh-verma @jaskirat2000 @vaibhavdaren Since the issue creator did not respond to my request, Can I take this issue?

**Comment by capedcrusader23** [comment]
you can work on this issue @tanujvyas10

**Comment by tanujvyas10** [comment]
> you can work on this issue @tanujvyas10

thank you sir
