### ISSUE TITLE
Settings menu is hidden behind logout Icon in dashboard.

### ISSUE THREAD

**Issue by Rupeshiya** [codeuino/social-platform-donut-frontend#357]
To check go to /settings route and check that both log out and settings icons are overlapping over each other.
**NEED TO BE FIXED**

**Comment by tanujvyas10** [comment]
hey @Rupeshiya , I would like to work on this

**Comment by Rupeshiya** [comment]
Yes, you can go aheah @tanujvyas10.

**Comment by tanujvyas10** [comment]
@Rupeshiya hey, I was trying to sync the frontend master repo with my local repo but its not synchronizing .Did you face any problem like this ?

**Comment by Rupeshiya** [comment]
@tanujvyas10 Only thing you have to do is to update your local branch with development branch not master.
you can run this to update your local branch code with development branch code:
```
git remote add upstream <git-url-of-front-end-repo>
git pull upstream development
```

**Comment by tanujvyas10** [comment]
@Rupeshiya I just did that, now it is showing
**This branch is 2 commits ahead, 6 commits behind codeuino:master.**
