### ISSUE TITLE
Add the updated fields in the signup page

### ISSUE THREAD

**Issue by Rupeshiya** [codeuino/social-platform-donut-frontend#375]
**Present scenario:**
As of now only, there is an email and password field for registering the user
Look at the backend repo database for user to get register and add those fields.

**Expectation:** 
The signup page should have updated fields

**Comment by tanujvyas10** [comment]
@Rupeshiya , I would like to work on this

**Comment by Rupeshiya** [comment]
ok, but make sure you use material design also look at the database schema and also routes to create the user.
You can go ahead.

**Comment by tanujvyas10** [comment]
@Rupeshiya sure, thanks
