### ISSUE TITLE
Fix UI for Social Logins, Add buttons should work..

### ISSUE THREAD

**Issue by sdsahib** [codeuino/social-platform-donut-frontend#38]
Fix the Social login button present on the dashboard, backend api is already linked. You have to fix the styles and make sure user is able to click them.

**Comment by jaskirat2000** [comment]
Okk

**Comment by kartikpandey2** [comment]
@sdsahib  I am willing to work on this issue but I am not able to find the social login button.

**Comment by ayush9898** [comment]
Can I work on this issue now ?

**Comment by arghac14** [comment]
@sdsahib Can I work on this?

**Comment by sdsahib** [comment]
@jaskirat2000 kindly guide the contributors..thanks
