### ISSUE TITLE
Implement UI part for the organisation

### ISSUE THREAD

**Issue by Rupeshiya** [codeuino/social-platform-donut-frontend#385]
**Present Scenario**
As of now, there is no UI for adding an organization's information.

**Expected outcome:**
Add popup to add organization information.

**Additional context:**
Please check the schema for the required input fields.

**Comment by tanujvyas10** [comment]
@Rupeshiya are u working on this?
if not then I would like to work on this

**Comment by Rupeshiya** [comment]
Sure @tanujvyas10 But just keep in mind to use material-UI also look at the required fields from backend repo.

**Comment by tanujvyas10** [comment]
very well thanks

**Comment by Rupeshiya** [comment]
@tanujvyas10  On another part of UI for organization @DevanshCodes  is working in another issue ( #386 ), so you both can sync with each other for no conflicts and better implementation
as of now, you can add the button in the organization page itself for popups and later on after @DevanshCodes  is done with the org tab, then we just need to add that button on the updated organization tab.

**Comment by tanujvyas10** [comment]
great

**Comment by Rupeshiya** [comment]
Closing this issue as merged with #387
