### ISSUE TITLE
Implementation of UI for entire Projects domain

### ISSUE THREAD

**Issue by tanujvyas10** [codeuino/social-platform-donut-frontend#389]
**Current Scenario**
Currently, there is no UI for projects domain

**Expected results**
Create the UI for all the functionalities belong to **projects** domain.
This includes the following:
- Dedicated page for projects showing all the projects in cards format(for brief details of each project)
- Popper for creating the new project(trigger via button)
- Popper for editing any project
- Popper when deleting any project
- clicking on a card will redirect the user to a new page showing a complete configuration of the selected project like the list of contributors, a list of maintainers, description, etc.

@devesh-verma @vaibhavdaren @jaskirat2000 
Can you please confirm whether these UI components are legit for donut platform or not
 
Please suggest the improvements or changes if needed
**I am working on this**

**Comment by harsh253** [comment]
Please describe the issue. What do you mean by projects domain ?
