### ISSUE TITLE
Logo of Organization is not available at its landing page

### ISSUE THREAD

**Issue by tanujvyas10** [codeuino/social-platform-donut-frontend#394]
**Current Situation**
When the user re-direct to the organization page, it doesn't have any logo/icon along with other details of the organization
![image](https://user-images.githubusercontent.com/48439116/78394829-fbd45000-7609-11ea-8f73-30ae8644c772.png)

**Expected Outcome**
The Logo should be present at organization page
![image](https://user-images.githubusercontent.com/48439116/78393912-5076cb80-7608-11ea-9065-1df661f3ab5e.png)

**Working on it**

**Comment by Rupeshiya** [comment]
Already implemented by @DevanshCodes in #390 
So @tanujvyas10 Please close this issue
