### ISSUE TITLE
Implementing the Pop-Up for adding new Project

### ISSUE THREAD

**Issue by DevanshCodes** [codeuino/social-platform-donut-frontend#401]
Currently there's no pop-up when clicked on Project button on Dashboard, there should be a pop-up on clicking that button. Hence, implementing that.

![image](https://user-images.githubusercontent.com/48180687/78469293-6cc85480-773d-11ea-9192-df41d7e40d96.png)

Working on it.

**Comment by tanujvyas10** [comment]
@DevanshCodes hey, i am already working on this
