### ISSUE TITLE
Refactor Frontend css

### ISSUE THREAD

**Issue by AuraOfDivinity** [codeuino/social-platform-donut-frontend#402]
**Issue**
The frontend CSS is fragmented and is disorganized and requires refactoring. 

**Additional Context**
I'll be working on this issue.

**Comment by tanujvyas10** [comment]
@AuraOfDivinity are you still working on this?

**Comment by AuraOfDivinity** [comment]
@tanujvyas10  Yes

**Comment by tanujvyas10** [comment]
nice good luck
if need any help just let me know
