### ISSUE TITLE
Dashboard landing page conversion to MaterialUI

### ISSUE THREAD

**Issue by rak-shit** [codeuino/social-platform-donut-frontend#405]
**Description**

Convert the dashboard landing page into MaterialUI

**Additional Context**

Working on it

**Comment by theprover97** [comment]
@rak-shit I am currently working on converting the pinned-posts/news-feed to Material-UI. You can leave that part to me.

**Comment by rak-shit** [comment]
> @rak-shit I am currently working on converting the pinned-posts/news-feed to Material-UI. You can leave that part to me.

Sure :)

**Comment by theprover97** [comment]
@rak-shit I have updated the Pinned-Posts and Updates section to Material-UI in PR #408 , you can use those components here.

**Comment by rak-shit** [comment]
@theprover97, seems like the conversion of dashboard to Material-UI is taken care. There is a PR for navigation already, the pinned-posts page and account page is taken care by you and there is another PR related to the org page. Is there anything left?

**Comment by theprover97** [comment]
Yeah, we have the following components to be improved:- Notifications, Portfolio and Upcoming-Events. You can convert those, and bundle up all other components as well.

**Comment by rak-shit** [comment]
> Yeah, we have the following components to be improved:- Notifications, Portfolio and Upcoming-Events. You can convert those, and bundle up all other components as well.

Okay, thanks for letting me know. I’ll be on it now :)

**Comment by theprover97** [comment]
Sure. Keep up the work!
