### ISSUE TITLE
New UI pf landing page ( frontend only )

### ISSUE THREAD

**Issue by jaskiratsingh2000** [codeuino/social-platform-donut-frontend#41]
New UI of landing page

**Comment by tharun143** [comment]
Can I take this issue? If yes what are all the requirements?

**Comment by jaskirat2000** [comment]
This page needs to have new UI but its approch should be different.
Like we have pages in facebook, twitter "feeds page" only

**Comment by tharun143** [comment]
So the issue is that we have to change the entire UI for this project.

**Comment by tharun143** [comment]
But the issue is only about the Landing page right?

**Comment by jaskirat2000** [comment]
Not full UI. Only the landing page.
Landing page here means the first page that the user gets after logging in.

**Comment by sarthak77** [comment]
Is this issue taken?

**Comment by tharun143** [comment]
yes @sarthak77

**Comment by tharun143** [comment]
@jaskirat2000 Are u talking about this page.
If yes I have to change the UI for this landing page. r8?
![Screenshot from 2019-03-10 13-43-09](https://user-images.githubusercontent.com/41537996/54082365-8f215000-433a-11e9-99a3-e798a6b9ed61.png)

**Comment by tharun143** [comment]
@jaskirat2000 Can u explain the issue briefly?
