### ISSUE TITLE
UI for Upcoming Events in Material-UI

### ISSUE THREAD

**Issue by rak-shit** [codeuino/social-platform-donut-frontend#410]
Changing the UI for upcoming event component into Material-UI

**Working on it**

**Comment by tanujvyas10** [comment]
Hey,@rak-shit I am Already working on this
 #389

**Comment by tanujvyas10** [comment]
hey.@rak-shit Ca, you please state the proper description of your project

**Comment by rak-shit** [comment]
> hey.@rak-shit Can, you please state the proper description of your issue

Done.
