### ISSUE TITLE
Changing UI for notifications component into Material-UI

### ISSUE THREAD

**Issue by rak-shit** [codeuino/social-platform-donut-frontend#412]
**Description** : Changing UI for notifications component into Material-UI. As of now it is written in basic HTML.

**Additional Context** : Working on it.

**Comment by tanujvyas10** [comment]
@rak-shit hey are you still working on this?

**Comment by rak-shit** [comment]
> @rak-shit hey are you still working on this?

Yes @tanujvyas10

**Comment by tanujvyas10** [comment]
> > @rak-shit hey are you still working on this?
> 
> Yes @tanujvyas10

nice good luck
if need any help just let me know
