### ISSUE TITLE
UI for the Account Tab

### ISSUE THREAD

**Issue by DevanshCodes** [codeuino/social-platform-donut-frontend#413]
Currently the UI of the account tab looks like:
![image](https://user-images.githubusercontent.com/48180687/78921313-5b22dc00-7ab2-11ea-9a04-fb28ae49b6c8.png)

It should look like:
![image](https://user-images.githubusercontent.com/48180687/78921356-68d86180-7ab2-11ea-9183-63de41a61a93.png)

Hence, addition of more components and styling of existing components is required.
Working on it!

**Comment by tanujvyas10** [comment]
@DevanshCodes hey are you still working on this issue?

**Comment by DevanshCodes** [comment]
> @DevanshCodes hey are you still working on this issue?
> 

Yeah I'm working on it.

**Comment by tanujvyas10** [comment]
cool if you need any help 
just let me know happy coding
