### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by Sweta271097** [codeuino/social-platform-donut-frontend#43]
To update the README with the new UI.

**Comment by tharun143** [comment]
Is this issue still open?... If yes please reply to my msg ASAP. :)
I want to know how to update the README.md file with what contents?

**Comment by tharun143** [comment]
Is this issue still open? 
please reply?

**Comment by jaskirat2000** [comment]
Yes please go ahead

**Comment by tharun143** [comment]
But what all the contents I have to add in the README.md?

**Comment by tharun143** [comment]
@jaskirat2000 Already Sweta she updated the README.md file with the landing images what else I have to do? Already it was updated.

**Comment by tharun143** [comment]
What else I have to do? PLease reply to this msg ASAP

**Comment by jaskirat2000** [comment]
Please make the size of images properly on the Readme with proper alligning
and avoid replication of images.
Reduce the size

**Comment by tharun143** [comment]
@jaskirat2000 There is a problem while setting up the MongoDB It was mentioned that add the MongoDB URL in the credentials.js file But I have to add the URL in which block?  please elobarate it..

**Comment by jaskirat2000** [comment]
@devesh

**Comment by jaskirat2000** [comment]
He can be better guide you about the same

**Comment by tharun143** [comment]
ok

**Comment by shreyanshjn** [comment]
@tharun143 you have to add the url in the '**database**' option in credential.js like this:-
database: 'your_mongo_url'

**Comment by tharun143** [comment]
module.exports = {
  oauth: {
    clientID: "192695093229-kf95jtdv1jge25d86ak99e68dkrpu33o.apps.googleusercontent.com",
    clientSecret: "rXvfxBahDlJF1ORk7y660XM8"
  },
  database: 'mongodb://tharun143:9182467224@tmcluster-shard-00-00-rj7ki.mongodb.net:27017,tmcluster-shard-00-01-rj7ki.mongodb.net:27017,tmcluster-shard-00-02-rj7ki.mongodb.net:27017/test?ssl=true&replicaSet=Tmcluster-shard-0&authSource=admin&retryWrites=true',
  github: {
    clientID: 'c9afdb238ed98b213912',
    clientSecret: '3031efea8badea1381da682fd5f21e88e5a15d2f'
  },
  facebook: {
    clientID: '383717979035587',
    clientSecret: '82bd80d286ef6e45606da6d53a97efbc'
  }
}

**Comment by tharun143** [comment]
@shreyanshjn Is this the way I have to write?

**Comment by shreyanshjn** [comment]
> @shreyanshjn Is this the way I have to write?

Yes @tharun143

**Comment by tharun143** [comment]
@jaskirat2000  I guess now you can close the issue. I modified the images and removed the extra images and added headers to the respective images.

**Comment by tharun143** [comment]
@jaskirat2000 Is there any updates to do? If yes please tell me.

**Comment by tharun143** [comment]
@shreyanshjn

 database: 'const MongoClient = require('mongodb').MongoClient; const uri = "mongodb+srv://tharun143:9182467224@tmcluster-rj7ki.mongodb.net/test?retryWrites=true";const client = new MongoClient(uri, { useNewUrlParser: true });client.connect(err => {const collection = client.db("test").collecti("devices");// perform actions on the collection objectclient.close();});',
                                          ^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/tharun/Social-Platform-Donut/config/google.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

After attaching the URL I got these errors Do you have any idea what to do?
