### ISSUE TITLE
Wireframes of Feedback page

### ISSUE THREAD

**Issue by Sweta271097** [codeuino/social-platform-donut-frontend#45]
Making new wireframes for the feedback page

**Comment by jaskirat2000** [comment]
Where are you placing it or plqns to ?

**Comment by Sweta271097** [comment]
@jaskirat2000 As of now, I'm just making a PR for the wireframes of the feedback page which I have placed in the folder "views". It's an simple idea about how it will look like. But there will be better variations when I actually implement it in html, css and JS.

**Comment by jaskirat2000** [comment]
Sounds good
