### ISSUE TITLE
Fix indentation,formatting and add comments for all the routes.

### ISSUE THREAD

**Issue by nityanandagohain** [codeuino/social-platform-donut-frontend#48]
A lot of the code in the repository is not formatted and the routes are not properly commented which becomes difficult for a new user to navigate.

I would like to a format and comment the code part by part.

**Comment by jaskirat2000** [comment]
This is really appreciable...I would be happy to get involve with you on
this .
So go ahead and yes be active for problems you face in the slack channel

**Comment by prateekiiest** [comment]
is this being currently worked upon?
