### ISSUE TITLE
Implement notification system for frontend using socket.io and integrate backend for notifications

### ISSUE THREAD

**Issue by Rupeshiya** [codeuino/social-platform-donut-frontend#485]
**Present scenario:**
As of now, there is no frontend for the notification system, so users of the platform would not be able to get any type of real-time notifications. Like if any event is going to be hosted by the org, or org is kept under maintenance, or user A follows user B, etc. So in all those cases, the user will not be able to get any notifications

**Expected scenario:**
Users of the platform should be able to get the notifications in realtime.

**Additional context:**
Working on it.

**Comment by jaskiratsingh2000** [comment]
What's the status?

**Comment by Rupeshiya** [comment]
done! Closing!
