### ISSUE TITLE
Broken links in README.

### ISSUE THREAD

**Issue by garimasingh128** [codeuino/social-platform-donut-frontend#493]
In the README section,
In the community section, following links are broken:
- @Mailing List.
- @Codeuino Wiki..
- Slack link. (It shows This link is no longer active
To join this workspace, you’ll need to ask the person who originally invited you for a new link.)

**Comment by jaskiratsingh2000** [comment]
Thanks for opening up the issue

**Comment by govindgoel** [comment]
I would like to work on this.

**Comment by jaskiratsingh2000** [comment]
Sure go ahead
