### ISSUE TITLE
Needed UI fix for jisti box

### ISSUE THREAD

**Issue by nisarg1499** [codeuino/social-platform-donut-frontend#516]
### Problem to be solved
Current JITSI integration UI is not proper. Buttons are not alligned and also some text is not aligned in a single line. Also size of buttons are not similar and there is unecessary scroll bar shown in the box. 
I am attaching the current UI.
![old-jitsi](https://user-images.githubusercontent.com/32075827/87327771-2495ab00-c552-11ea-809f-f9caad007ac3.png)

**Comment by vaibhavdaren** [comment]
All the best first issue 🐤

**Comment by nisarg1499** [comment]
I have attached the photo of jitsi box of master branch. I am attaching the new photo of development branch which needs changes.
Only the button and text allignment changes are needed. Other things are already fixed.
![jitsi1](https://user-images.githubusercontent.com/32075827/87330554-6163a100-c556-11ea-9dc9-ff14cd85194f.png)
