### ISSUE TITLE
[Testing] Report User on a failed attempt for login action on login page

### ISSUE THREAD

**Issue by kmehant** [codeuino/social-platform-donut-frontend#533]
## Problem
Presently User is not being reported if the server throws a Bad Request for an invalid login on the login page.

Link: https://deploy-preview-530--codeuino-donut.netlify.app/

## How to Reproduce
Move to https://deploy-preview-530--codeuino-donut.netlify.app/ and try login with some random email and password and you can see the user is not notified.

**Comment by Rupeshiya** [comment]
Working on it
