### ISSUE TITLE
[testing] - The cursor does not change, when hovering over the delete button for a comment.

### ISSUE THREAD

**Issue by Priyanka488** [codeuino/social-platform-donut-frontend#536]
### Problem

For deleting a comment, the cursor does not change when hovered over the delete button.

### How to Reproduce?

1. Go to https://deploy-preview-530--codeuino-donut.netlify.app/
2. Click on the comment section of any post.
3. Hover over the delete button, next to a comment.

**Comment by jaskiratsingh2000** [comment]
Thanks for opening this up
