### ISSUE TITLE
[Testing] - Creates invite without clicking on Invite option automatically

### ISSUE THREAD

**Issue by jaskiratsingh2000** [codeuino/social-platform-donut-frontend#540]
## Problem to be solved

When we want to invite any new member to the platform and clicks on the "Member" option available in the top right column we see a pop-up and on clicking the input field multiple times it keeps creating the Invite link without copying the link or clicking the button.

## Testing demonstration

![20200730_124150](https://user-images.githubusercontent.com/10228651/88892399-8bc18980-d1f9-11ea-945a-ff80c0d12536.gif)

**Comment by Rupeshiya** [comment]
Working on it.
