### ISSUE TITLE
Delete event popup don't close even after event is deleted

### ISSUE THREAD

**Issue by ayushnagar123** [codeuino/social-platform-donut-frontend#547]
### Demo video
[Reference issue demo](https://drive.google.com/file/d/1IszcyFoJ8cHrOo5tSFC1e-YX47juBADj/view?usp=sharing)
### Solution
Once he issue is deleted and status code of successful deletion is recieved, the modal box must close automatically.

**Comment by lazycipher** [comment]
Already fixed! May be closed @vaibhavdaren.
