### ISSUE TITLE
Cards of event page dates overlaps the edges

### ISSUE THREAD

**Issue by ayushnagar123** [codeuino/social-platform-donut-frontend#548]
### Demo Screenshot
for some screen sizes as discussed above of 768px width.
- [ ] Screen size=>1440x1024
![image](https://user-images.githubusercontent.com/32647423/89121012-c9affd80-d4d8-11ea-937c-8b8a86e7ef5c.png)
- [ ] Screen size=> 1152x700
![image](https://user-images.githubusercontent.com/32647423/89121090-7c805b80-d4d9-11ea-9583-ad99d43f98f5.png)
- [X] Screen Size => 1080 x 720
![image](https://user-images.githubusercontent.com/32647423/89121119-ac2f6380-d4d9-11ea-817d-0cdd107aee37.png)
- [ ] Screen size => 800 x 1280
![image](https://user-images.githubusercontent.com/32647423/89121147-f7e20d00-d4d9-11ea-9280-5a95ba0327e9.png)

**Comment by lazycipher** [comment]
Fixed in #641 
@vaibhavdaren please close
