### ISSUE TITLE
Navbar issues needed to be fixed

### ISSUE THREAD

**Issue by ayushnagar123** [codeuino/social-platform-donut-frontend#549]
### screenshot demo
![image](https://user-images.githubusercontent.com/32647423/89121268-18f72d80-d4db-11ea-9052-053e1a0d80e0.png)
### Fix needed
* Donut icon not centraqlly aligned in icon section.
* logout tab not alligned with other tabs
* only logout tb is fixed in sidenavbar rest of the navbar is not fiex which looks too odd. Either fix the whole navbar or non of the tabs shall be fixed.
![image](https://user-images.githubusercontent.com/32647423/89121515-2d3c2a00-d4dd-11ea-9d0d-6abe7ddaf266.png)

**Comment by Rupeshiya** [comment]
ref: #539

**Comment by divanshurox** [comment]
I am new to open source can I work on this??

**Comment by lazycipher** [comment]
Can we close this @vaibhavdaren?
