### ISSUE TITLE
Improper date formating needs to be fixed

### ISSUE THREAD

**Issue by ayushnagar123** [codeuino/social-platform-donut-frontend#550]
### Screenshot demo
![image](https://user-images.githubusercontent.com/32647423/89121360-daae3e00-d4db-11ea-83a1-028938984b32.png)
![image](https://user-images.githubusercontent.com/32647423/89121387-2b259b80-d4dc-11ea-90cf-26faccf2e4db.png)
![image](https://user-images.githubusercontent.com/32647423/89121399-4e504b00-d4dc-11ea-931f-21563353ebbd.png)
### Solution
Dates of default format needs to be converted to understandable date and time format.

**Comment by Rupeshiya** [comment]
Working on it
