### ISSUE TITLE
Non responsive model box for member section of organization

### ISSUE THREAD

**Issue by ayushnagar123** [codeuino/social-platform-donut-frontend#552]
### Test url
https://deploy-preview-530--codeuino-donut.netlify.app/
### demo Screenshot
- [ ] Screen size => 1440xx900
![image](https://user-images.githubusercontent.com/32647423/89121713-e7806100-d4de-11ea-8e22-d09cb53029c9.png)
- [ ] Screen size => 768 x 1024
![image](https://user-images.githubusercontent.com/32647423/89121738-20b8d100-d4df-11ea-8dc7-e24f442c6a53.png)

**Comment by mishrasushruti99** [comment]
Can I work on this?

**Comment by lazycipher** [comment]
Fixed in #658
