### ISSUE TITLE
Unnecessary pages in events

### ISSUE THREAD

**Issue by tushar912** [codeuino/social-platform-donut-frontend#579]
![bug](https://user-images.githubusercontent.com/59223034/90664216-4d534380-e268-11ea-86f5-1a78dd2017a6.gif)
Even though only the first page has content 10 pages are available same issue in other pages.

**Comment by Rupeshiya** [comment]
These are not pages @tushar912 Please check the pagination code.

**Comment by tushar912** [comment]
oh sorry my mistake
