### ISSUE TITLE
Integration of front end and backend.

### ISSUE THREAD

**Issue by capedcrusader23** [codeuino/social-platform-donut-frontend#61]
The front end and backend of platform is not integrated.
It is important to integrate for version 1.

**Comment by sdsahib** [comment]
Is it done? If not, is both frontend and backend ready.

**Comment by jaskirat2000** [comment]
It is yet to be done

**Comment by sdsahib** [comment]
Okay, do we have both front-end part and back-end part ready?

**Comment by capedcrusader23** [comment]
we are working on it,as we progress we will be integrating both.

**Comment by sarthak77** [comment]
I'll take this up

**Comment by jaskirat2000** [comment]
So please go ahead

**Comment by sarthak77** [comment]
I'll take this up

**Comment by sarthak77** [comment]
@jaskirat2000 can you tell the files and branch to modify for this?

**Comment by jaskirat2000** [comment]
@capedcrusader23 can you help in this

**Comment by sarthak77** [comment]
@capedcrusader23 can you comment on the thread
Thanks
