### ISSUE TITLE
[Bug Report] Inconsistency in UI

### ISSUE THREAD

**Issue by codetheorem** [codeuino/social-platform-donut-frontend#617]
![screencapture-localhost-3000-org-settings-1599499535427](https://user-images.githubusercontent.com/54779517/92409203-61021380-f15d-11ea-80ad-0f0205414454.png)

There is inconsistency in UI the above page. Also when we press the pagination below it shows an error either it should show 404 or should be dynamic.

**Comment by Rupeshiya** [comment]
@codetheorem Add the screenshot of eror

**Comment by codetheorem** [comment]
@Rupeshiya check this.

![screencapture-localhost-3000-org-settings-1599544087189](https://user-images.githubusercontent.com/54779517/92437681-1916d700-f1c5-11ea-9f0f-d0225dbf176e.png)

**Comment by lazycipher** [comment]
I see as of now the `total` props of `Pagination` is set to `500` by default. As of now, we're mapping the users' list on this page. So, as per my suggestion, setting the `total` to `{users.length}` will solve this pagination problem.

**Comment by lazycipher** [comment]
Fixed in https://github.com/codeuino/social-platform-donut-frontend/pull/641
Please close @vaibhavdaren, @jaskiratsingh2000
