### ISSUE TITLE
[Bug Report] Edit button not functional.

### ISSUE THREAD

**Issue by codetheorem** [codeuino/social-platform-donut-frontend#618]
![screencapture-localhost-3000-settings-1599499705178](https://user-images.githubusercontent.com/54779517/92409306-c6560480-f15d-11ea-92a5-7d306db05f84.png)

The edit button is not functional on the above page.

**Comment by Rupeshiya** [comment]
@codetheorem Edit is allowed only when allowed by admin.
closing this issue

**Comment by codetheorem** [comment]
@Rupeshiya I gave permission to edit the name and email address from the org settings but still it is not working .
