### ISSUE TITLE
[Bug Report] See more button not visible.

### ISSUE THREAD

**Issue by codetheorem** [codeuino/social-platform-donut-frontend#619]
See more button is not visible in the project card in the projects section.

![screencapture-localhost-3000-projects-1599545732272](https://user-images.githubusercontent.com/54779517/92439713-f71f5380-f1c8-11ea-85c3-8a7870f57b2b.png)

**Comment by arkumari2000** [comment]
Hey, I want to give it a try.
Can you assign me this issue?
Thank you.

**Comment by lazycipher** [comment]
Fixed in #641 
@vaibhavdaren we may close this.

**Comment by jaskiratsingh2000** [comment]
Sure go ahead
