### ISSUE TITLE
[BUG]Update the navigation panel in proposal route.

### ISSUE THREAD

**Issue by AuraOfDivinity** [codeuino/social-platform-donut-frontend#636]
**Describe the bug**
The navigation bar on the left-hand side of the proposal related pages is not properly updated. (Check the attached images below)

**Steps to Reproduce**
1. Log in.
2. Visit the organization page using the organization tab on the left-hand side navigation bar.
3. Click on the "propose an idea button".

**Expected behavior**
The navigation bar should properly be styled and appear as it appears on the other pages.

**Screenshots**
![image](https://user-images.githubusercontent.com/31003923/94630931-c375ac00-02e4-11eb-90e5-c6e13a244b8c.png)

![image](https://user-images.githubusercontent.com/31003923/94631013-f15af080-02e4-11eb-9192-519074937ec3.png)

**Additional context**
Have a look at the following PR to get a better idea about the changes done to update the left-hand side navigation panel.

https://github.com/codeuino/social-platform-donut-frontend/pull/571

**Comment by varunks99** [comment]
@AuraOfDivinity, can I take up this issue?

**Comment by jaskiratsingh2000** [comment]
Sure, go ahead

**Comment by rajprakash00** [comment]
@AuraOfDivinity  I think this issue has already been resolved as a part of this [PR](https://github.com/codeuino/social-platform-donut-frontend/pull/623)
It's preview: [link](https://deploy-preview-623--friendly-sinoussi-3b191b.netlify.app/proposaleditor)

**Comment by lazycipher** [comment]
Already Solved in https://github.com/codeuino/social-platform-donut-frontend/pull/641
@vaibhavdaren @jaskiratsingh2000, please close
