### ISSUE TITLE
Improve testability of code 

### ISSUE THREAD

**Issue by capedcrusader23** [codeuino/social-platform-donut-frontend#75]
Code base is not tested.
use mocha to test codebase

**Comment by jaskirat2000** [comment]
Can you ellaborate this more on how to get on things with proper links etc

**Comment by TG1999** [comment]
Assign this issue to me

**Comment by jaskirat2000** [comment]
Sure go ahead

**Comment by TG1999** [comment]
I have written first test for checking if user is added successfully or not #87 please merge it

**Comment by TG1999** [comment]
I have installed dev dependencies in package.json and made a PR for same #92

**Comment by sdsahib** [comment]
Hey, you are printing the output to the console, instead assert the response from the REST APIs.

**Comment by TG1999** [comment]
> Hey, you are printing the output to the console, instead assert the response from the REST APIs.

Hey, Since in response you are rendering a view so how can I assert a view.

**Comment by TG1999** [comment]
And please merge #92 it has packages installed as dev dependencies

**Comment by sdsahib** [comment]
You should check the status of the page in the then block like :-  **res.status.should.equal(200);**
you should check the data you send in the test case, is received at the front-end view, like **res.body.data[0].should.include.keys(
        'id', 'username',
 );**

**Comment by TG1999** [comment]
#92 made the changes for response status and checking heading CODEUINO successfully please check

**Comment by sdsahib** [comment]
Main reason of writing the test cases is to check the behavior of code for both success conditions and for failing (boundary conditions).
You have already written the test cases for success conditions(👍) and you should also write the fail test test for the routes,(when are they going to fail-> boundary cases).

**Comment by sdsahib** [comment]
Tip:- Test cases will be read mostly by the business not the technical guys.
So you test cases should be easily readable, always try to create and variable and then send use, try using proper messages for it blocks.
