### ISSUE TITLE
Provide 2 color Scheme for donut platform

### ISSUE THREAD

**Issue by capedcrusader23** [codeuino/social-platform-donut-frontend#78]
![ss](https://user-images.githubusercontent.com/37747717/53483040-988efa80-3aa6-11e9-882f-208592c141cb.jpg)

The current color theme of Donut is black and white.
We want to design a night theme for platform.
Provide good suggestions and work on it to improve UI.

**Comment by lakshyabatman** [comment]
Yes, sure we can discuss about it and let me work on it! 😊

**Comment by khusi-anu** [comment]
Can I work on this?

**Comment by jaskirat2000** [comment]
Sure if lakshay is not on it

**Comment by ArchitaDesai** [comment]
Can I work on this issue, @jaskirat2000 @capedcrusader23 since no one else has commented for a week?

**Comment by jaskirat2000** [comment]
Sure. This would be appreciable
