### ISSUE TITLE
Make the feeds portion scrollable 

### ISSUE THREAD

**Issue by capedcrusader23** [codeuino/social-platform-donut-frontend#79]
![ss](https://user-images.githubusercontent.com/37747717/53484927-fc1b2700-3aaa-11e9-9cde-ab87406039af.jpg)

If you start server and try to scroll page,whole section of proposed project and and open source events also get scrolled. 
Make those 2 fixed and move open source event to left of feeds.

**Comment by ani-sha** [comment]
I would like to work on this issue

**Comment by Vaibhavraj10** [comment]
Is anybody else working on this issue?

**Comment by ani-sha** [comment]
@capedcrusader23 I am working on this issue but I am facing some issues. I have made the feeds section scrollable but it's difficult to write media queries for smaller screens due to lot of dependencies from external css files. Will I raise a PR with my current changes?

**Comment by shahkv95** [comment]
Heyy @capedcrusader23 I can solve this issue. May I proceed for the same?

**Comment by piyush97** [comment]
> Heyy @capedcrusader23 I can solve this issue. May I proceed for the same?

Yes

**Comment by capedcrusader23** [comment]
Sure you can work on it
