### ISSUE TITLE
Remove Search button and add font-awesome magnifying glass icon in search bar 

### ISSUE THREAD

**Issue by capedcrusader23** [codeuino/social-platform-donut-frontend#80]
![ss2](https://user-images.githubusercontent.com/37747717/53485578-929c1800-3aac-11e9-9fad-ad0bc462e8e7.jpg)

![ss3](https://user-images.githubusercontent.com/37747717/53485672-dabb3a80-3aac-11e9-9e95-6c63b2df47e2.jpg)

Try to change the navbar of donut from former to latter

**Comment by thobhanifreddy** [comment]
can I work on this issue?

**Comment by jaskirat2000** [comment]
Make sure we ask for the backend also for this

**Comment by thobhanifreddy** [comment]
@jaskirat2000 should I ask for it in slack?

**Comment by pradnyasd** [comment]
@devesh-verma  is anyone working on this issue? or should I start with it?

**Comment by thobhanifreddy** [comment]
@pradnyasd I will open PR in few hours.

**Comment by sarthak77** [comment]
@jaskirat2000 doesn't it conflict with issue #13?

**Comment by jaskirat2000** [comment]
Opps I think yes, please close this issue Thanks
