### ISSUE TITLE
Implement an edit button, which when clicked enables user to edit all the fields. And the edit button changes too Save button.

### ISSUE THREAD

**Issue by capedcrusader23** [codeuino/social-platform-donut-frontend#81]
![image](https://user-images.githubusercontent.com/37747717/53486368-8618bf00-3aae-11e9-9036-7600cec07b4b.png)
Remove the change button and add a single button to change all the fields once clicked on button all fields should be editable and button should change to 'save'.

**Comment by khusi-anu** [comment]
I would like to work on this. May I?

**Comment by mark-nakachon** [comment]
I will work on this I will add the option to edit the entire bio and I will use Axios library to make a post request to the /updatebio route and change the udpatebio function inside profile.controller.js to save the data to MongoDB database. if necessary I will also some validation in the routes using [Joi](https://www.npmjs.com/package/joi) May I ?

**Comment by invincibleJai** [comment]
@mark-nakachonI guess @khusi-anu is working on it. @khusi-anu pls let us know if you are not.

**Comment by mark-nakachon** [comment]
if u assign me for this i can fix it in less than an hour

**Comment by khusi-anu** [comment]
@mark-nakachon Go ahead

**Comment by mark-nakachon** [comment]
I resolved this issue and made a pull request  please review it

**Comment by mark-nakachon** [comment]
please close this issue as it is resolved
