### ISSUE TITLE
Change the look and feel of the like, dislike, comment and share buttons

### ISSUE THREAD

**Issue by devesh-verma** [codeuino/social-platform-donut-frontend#83]
For inspiration have a look at twitter posts, where the number of likes and shares and comments are written beside the button. We need to have similar buttons.
![twitter_screenshot](https://user-images.githubusercontent.com/20336672/53486493-e27bde80-3aae-11e9-8e83-7e1b7dd5b861.png)

As of now, it looks like this:
![like_share_comment](https://user-images.githubusercontent.com/20336672/53488244-bd3d9f00-3ab3-11e9-97f7-4d76942e6c72.png)

**Comment by iamgrawal** [comment]
Hey @devshiva619, I would like to work on this issue.

**Comment by iamgrawal** [comment]
Sorry, by mistake I closed this issue.

**Comment by shivamluthra** [comment]
@iamgrawal Are you working on this issue?

**Comment by shreyanshjn** [comment]
I would like to work on this issue if anyone is not working on it.

**Comment by invincibleJai** [comment]
@shreyanshjn you may take only if @iamgrawal is not working on it. @iamgrawal pls confirm??

**Comment by iamgrawal** [comment]
Hey @shreyanshjn, you can work on this issue. I am working on some other issue right now, meanwhile you can complete it.

**Comment by capedcrusader23** [comment]
Hey anyone working on this??

**Comment by mark-nakachon** [comment]
if u assign this issue to me i can fix it in less than an hour
