### ISSUE TITLE
Improve the logic of upvote in donut

### ISSUE THREAD

**Issue by capedcrusader23** [codeuino/social-platform-donut-frontend#84]
Current logic in O(n)^2 make it O(1) by using maps instead of arrays

**Comment by lakshyabatman** [comment]
On it!😊

**Comment by lakshyabatman** [comment]
@capedcrusader23 @devshiva619 is this part of gssoc?

**Comment by lakshyabatman** [comment]
#93 , Schema is updated and will start working on AJAX calls for the same, :)

**Comment by Rupeshiya** [comment]
@capedcrusader23 , I think on every upvote or downvote updating the schema of  for upvote and downvote will take O(1) . we can do this if we take upvote and downvote as type number instead array of strings . Correct me if I am wrong .

**Comment by capedcrusader23** [comment]
@Rupeshiya, if you see maps as data type there we can develop a good logic,for eg
map<key,value>
key:-Eid of user
value:(+1,-1)
+1 if user not present then make it as key and value as +1 else make it -1

**Comment by lakshyabatman** [comment]
#106
