### ISSUE TITLE
Change the way user interacts with comment functionality, and the way comments are shown

### ISSUE THREAD

**Issue by devesh-verma** [codeuino/social-platform-donut-frontend#85]
To understand this - have a look at facebook comment button. 

Also, make it look like facebook comment button.
![screenshot 2019-02-27 at 4 32 08 pm](https://user-images.githubusercontent.com/20336672/53487261-17893080-3ab1-11e9-9a47-6fa3f7af0e30.png)

When you press the button then the comments are loaded.
![screenshot 2019-02-27 at 4 32 23 pm](https://user-images.githubusercontent.com/20336672/53487262-1821c700-3ab1-11e9-9157-9965c42928a2.png)

**Also, implement the view more functionality.**

**Comment by atharva3010** [comment]
Can I work on this issue ?

**Comment by jaskirat2000** [comment]
Sure go ahead

**Comment by shreyanshjn** [comment]
hey @atharva3010 are you working on this issue?

**Comment by atharva3010** [comment]
Yes
