### ISSUE TITLE
Improve the way tags look

### ISSUE THREAD

**Issue by devesh-verma** [codeuino/social-platform-donut-frontend#86]
For this, you can take inspiration from Github tags, also you free to show your creativity in this. 
You can also produce 2-3 variations if you want.

**Comment by iamgrawal** [comment]
Hey @devshiva619, can you elaborate more?

**Comment by iamgrawal** [comment]
I would like to work on this issue

**Comment by invincibleJai** [comment]
@iamgrawal sure you can and were you able to bring the project? if yes you can add project/see existing tags associated with projects. Task is to beautify those.

**Comment by amanbora** [comment]
I would like to contribute on this issue. Is it still active?

**Comment by jaskirat2000** [comment]
Sure. You can

**Comment by amanbora** [comment]
@jaskirat2000 thanks, are there any more specifics of the issue?

**Comment by amanbora** [comment]
<img width="908" alt="Screenshot 2020-01-25 at 12 33 20 AM" src="https://user-images.githubusercontent.com/33185170/73096290-739b4580-3f0a-11ea-9d5e-4f7b28bab733.png">
The `credential.js` seems missing

**Comment by amanbora** [comment]
Okay, I think I cloned the wrong repo.
