### ISSUE TITLE
Improve look of name,image and designation

### ISSUE THREAD

**Issue by devesh-verma** [codeuino/social-platform-donut-frontend#88]
As of now the alignment of image(user profile pic) and the name of the user and the designation is not proper.
Also, the profile pic is in square shape as now, change to circular one.
![name_designation](https://user-images.githubusercontent.com/20336672/53488375-14dc0a80-3ab4-11e9-882d-87a403fb40f8.png)

**Comment by atharva3010** [comment]
Can I work on this issue ?

**Comment by jaskirat2000** [comment]
Sure

**Comment by sarthak77** [comment]
Can I work on this?

**Comment by invincibleJai** [comment]
@sarthak77 , @atharva3010 is working on this I believe. @atharva3010 are you on it?

**Comment by sarthak77** [comment]
Yeah I saw but someone suggested me this issue from the slack channel

**Comment by invincibleJai** [comment]
wait for @atharva3010 to revert else you are pick up

**Comment by atharva3010** [comment]
I am working on it

**Comment by arghac14** [comment]
Anyone working on this? @atharva3010 @invincibleJai  @devshiva619 
If not I'd like to work.

**Comment by shahkv95** [comment]
Heyy @devshiva619 ! I believe that there's no PR since a long time. I wish to take up the task and contribute the earliest possible. May I please proceed for the same.

**Comment by amanbora** [comment]
Is the issue still on? I could work on it. Please assign it to me if its available.

**Comment by jaskirat2000** [comment]
Sure go ahead. Please

**Comment by amanbora** [comment]
Pls refer pull request #300
