### ISSUE TITLE
Improve the way content is shown in cards

### ISSUE THREAD

**Issue by devesh-verma** [codeuino/social-platform-donut-frontend#89]
As of now the content is not the main highlighted part of the feed, take make it look better you can have a look at other social media platforms.
![screenshot 2019-02-27 at 5 15 52 pm](https://user-images.githubusercontent.com/20336672/53488760-44d7dd80-3ab5-11e9-80e9-2535813a61dd.png)

**Comment by thisisabdus** [comment]
May I work on this issue, please?

**Comment by jaskirat2000** [comment]
Sure

**Comment by thisisabdus** [comment]
I am **not** working on this issue.

**Comment by shivamluthra** [comment]
Let me take up this issue :)

**Comment by invincibleJai** [comment]
@shivamluthra pls go ahead 👍

**Comment by sarthak77** [comment]
Is anyone working on this issue?

**Comment by shivamluthra** [comment]
@sarthak77 Yes I'm on it. Got a bit late, was working on something else before.

**Comment by shahkv95** [comment]
Heyy, I have worked on cards. 
I want to take up the task. 
**May I** ??

**Comment by shahkv95** [comment]
@devshiva619 Heyy! May I proceed for the same?

**Comment by pragun22** [comment]
is anyone still working on this issue or may I work on this?

**Comment by agarwalprashasti** [comment]
Can you please assign this issue to me?

**Comment by sarthak77** [comment]
I guess @shivamluthra is working on it

**Comment by agarwalprashasti** [comment]
But still it is not assigned to anyone.

**Comment by shivamluthra** [comment]
@agarwalprashasti @pragun22 @shahkv95 @sarthak77 If anyone wants to take up the issue can do it. I didn't do it because of one major reason that it won't be much of benefit since complete codebase needs to be migrated to vue and profile page, user dashboard & community dashboard are already supposed to be re-written completely.
cc @jaskirat2000 @devshiva619
