### ISSUE TITLE
Show timestamp

### ISSUE THREAD

**Issue by devesh-verma** [codeuino/social-platform-donut-frontend#90]
Display the timestamp.
![time_stamp](https://user-images.githubusercontent.com/20336672/53488978-d5162280-3ab5-11e9-8fee-bb4fa74dcc59.png)

**Comment by sweezy793** [comment]
I would like to work on this

**Comment by shakti97** [comment]
@devshiva619 where should i get this ,

**Comment by svr8** [comment]
Hey! I wanted to solve this issue.. got a little confused. Where should I add the timestamp? at the circled location or where it says in red "add timestamp".

**Comment by invincibleJai** [comment]
@sweezy793 are working on this?

**Comment by agarwalprashasti** [comment]
@devshiva619 Can you please assign this issue to me?

**Comment by mark-nakachon** [comment]
if u assign this issue to me i can fix it in less than an hour
