### ISSUE TITLE
The landing page on my local codebase is different from the one given on the readme

### ISSUE THREAD

**Issue by SarthakSri98** [codeuino/social-platform-donut-frontend#94]
This is the one on my local machine
![screenshot from 2019-02-28 05-43-35](https://user-images.githubusercontent.com/28146914/53567809-576e1780-3b86-11e9-989d-4610cad997f9.png)

and this is on the readme page of Social-platform-donut i.e. there is no auth login option for GitHub etc.
![screenshot from 2019-02-28 05-43-55](https://user-images.githubusercontent.com/28146914/53567709-12e27c00-3b86-11e9-97f5-8fe5a945c13a.png)
@devesh-verma sir

**Comment by lakshyabatman** [comment]
I have made more changes on the landing page and readme wasn't updated, please update it. :)

**Comment by lakshyabatman** [comment]
And there is button for login , click the get started button

**Comment by lakshyabatman** [comment]
The readme typos and old image issue was assigned to someone, though he haven't updated it yet.

**Comment by lakshyabatman** [comment]
#59

**Comment by jaskirat2000** [comment]
Please remove images that dirupts the whole prototype

**Comment by lakshyabatman** [comment]
@jaskirat2000 , I guess there are people who were assigned for the same , so we can close the issue :)

**Comment by jaskirat2000** [comment]
Ok

**Comment by shivamluthra** [comment]
@lakshyabatman Is this issue resolved? If yes, Please close this issue.

**Comment by lakshyabatman** [comment]
I'm not author the issue :) @shivamluthra .

**Comment by lakshyabatman** [comment]
Please close this issue @SarthakSri98
